-- DELETE
-- FROM players;
--
-- DELETE
-- FROM similiarplayers;
--
-- INSERT INTO players (playerid, college, userid)
--     VALUES(1, 'Duke', 3),
--           (2, 'King', 5),
--           (3, 'Queen', 5 );
--
-- INSERT INTO similiarplayers (similiarplayerid, college, playerid)
-- 	VALUES (1, 'Pawn', 1),
--            (2, 'Knight', 1),
--            (3, 'Bishop',  1),
--            (4, 'Rook', 2),
--            (5, 'King', 2),
--            (6, 'Queen',  3);
--
--
-- alter sequence hibernate_sequence restart with 20;